spring:
  #开发模式
  profiles:
    active: test

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:yude.mes.com.mes_yd.mapper: debug
